
export const data = [
	{
		name: "U.S.-Polo KRIS003-WHI",
		imagePath: ['https://kicks-sport.com/eng_pl_U-S-POLO-ASSN-KRIS003-WHI-White-Navy-Red-Sneakers-3895_1.jpg', 'https://kicks-sport.com/eng_pl_U-S-POLO-ASSN-KRIS003-WHI-White-Navy-Red-Sneakers-3895_2.jpg', 'https://kicks-sport.com/eng_pl_U-S-POLO-ASSN-KRIS003-WHI-White-Navy-Red-Sneakers-3895_1.jpg', 'https://kicks-sport.com/eng_pl_U-S-POLO-ASSN-KRIS003-WHI-White-Navy-Red-Sneakers-3895_4.jpg'],
		material:"textile",
		seasons:["autumn","summer"],
		size:[ '41', '43', '44'],
		sex:"male",
		color:['white', 'red'],
		description:'U.S.-Polo a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 310,
		rating: 4.2,
		category:'sneakers',
		bunerImg:"",
		id: 3046
	},
	{
		name: "Puma TARRENZ SB II OPEN ROAD",
		imagePath: ['https://i.sportisimo.com/products/images/1524/1524651/700x700/puma-138814_2.jpg', 'https://i.sportisimo.com/products/images/1524/1524655/700x700/puma-138814_4.jpg', 'https://i.sportisimo.com/products/images/1524/1524657/700x700/puma-138814_5.jpg', 'https://i.sportisimo.com/products/images/1524/1524645/700x700/puma-138814_1.jpg'],
		material:"leather",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['36', '37', '41'],
		sex:"male",
		color:['black'],
		description:'Men’s stylish shoes: The Puma TARRENZ SB II OPEN ROAD are perfectly comfortable, breathable and have a synthetic leather upper. The sole is made of high-quality rubber, which grips firmly to any surface and is stable. These shoes are suitable for casual daily wear and leisure time activities from autumn until spring. ',
		price: 180,
		rating: 4.3,
		category:'sneakers',
		id: 306
	},
	{
		name: "Nike Air Force 1",
		imagePath: ['https://www.1310.com.ua/wp-content/uploads/2022/10/krossovki-nike-air-force-1-07-lv8-dv3501-400-1.jpg', 'https://brooklynstore.com.ua/content/images/14/muzhskie-krossovki-nike-air-force-1-07-lv8-dq7659-101-0-99651292660094.webp', "https://brooklynstore.com.ua/content/images/14/muzhskie-krossovki-nike-air-force-1-07-lv8-dq7659-101-0-38227280880454.webp", "https://brooklynstore.com.ua/content/images/14/muzhskie-krossovki-nike-air-force-1-07-lv8-dq7659-101-0-34248424892690.webp"],
		material:"leather",
		bunerImg:"",
		seasons:["autumn", "spring", "summer", "winter"],
		size:['41', '42', '43'],
		sex:"male",
		color:['white', 'black', 'red'],
		description:'Air Force 1 sneakers, known by various monikers including Forces, AF1s, Uptowns, Flaves, and Harlems, hold a special place in the hearts of sneaker collectors worldwide. Nike Air Force 1s, released in 1982, are not just shoes – theyre a cultural phenomenon. These iconic sneakers introduced Nikes groundbreaking Air technology to the basketball shoe arena, forever changing the game. With its timeless AF1 silhouette, Nike crafted a versatile masterpiece that seamlessly blends style and functionality, making it a must-have for streetwear and sneaker enthusiasts. Coming off of the 40th Anniversary of the AF1, we delve into the captivating history of the Nike Air Force 1 and explore our collection of Air Forces for sale at our online Sneaker Shop.',
		price: 220,
		rating: 3.4,
		category:'sneakers',
		id: 234
	},
	{
		name: "Adidas USA 84 Trainers Burgundy",
		imagePath: ['https://i.ebayimg.com/images/g/1d4AAOSw5FdjXnRq/s-l1200.webp', "https://static.ftshp.digital/img/p/3/3/1/1/6/5/331165.jpg", "https://i.ebayimg.com/images/g/Y28AAOSwXu1jXnR0/s-l1600.jpg", "https://www.tradeinn.com/f/13765/137657246_5/adidas-originals-usa-84-trainers.jpg"],
		material:"leather",
		bunerImg:"",
		seasons:["autumn", "spring", "summer", "winter"],
		size:['41', '42', '43'],
		sex:"male",
		color:['white', 'black', 'red'],
		description:'The 80s are back. These adidas USA 84 Shoes bring back classic looks from the feet of the decades best athletes. A lightweight mesh upper, skinny 3-Stripes and a soft midsole all come straight from the archives. Fun colours freshen up the vibe.',
		price: 210,
		rating: 4.4,
		category:'sneakers',
		id: 236
	},
	{
		name: "Nike Blaze Mid 77 Vngt",
		imagePath: ['https://allstars.ua/upload/iblock/0bc/0bcd501e0a5344d35abd5faad4b8b2a0.jpg', "https://allstars.ua/upload/iblock/bf4/bf4d5ff9546f178450b88513fe77647c.jpg", "https://yesoriginal.com.ua/image/cache/catalog/other_images/BQ6806-100-4-472x497.webp", "https://images.prom.ua/3615061781_w600_h600_3615061781.jpg"],
		material:"leather",
		bunerImg:"",
		seasons:["autumn", "spring", "summer", "winter"],
		size:['38', '41', '42', '43'],
		sex:"male",
		color:['white', 'black', 'red'],
		description:'The Nike Blazer Mid Vintage 77 has a style that matches its retro design. Utilising a white leather construction, the Blazers upper features vintage-looking suede panels along both the side and toe box. A retro Nike logo appears on the tongue and old school “NIKE” typography appears on the heel.',
		price: 230,
		rating: 4.7,
		category:'sneakers',
		id: 237
	},
	{
		name: "Reebok Astroride Trail Gore-Tex 2.0",
		imagePath: ['https://images.prom.ua/2024999789_w640_h640_2024999789.jpg','https://obvi.com.ua/content/images/38/480x480l50nn0/muzhskie-krossovki-reebok-astroride-trail-gore-tex-2.0-dv5956-original-91505223166234.jpg', "https://brooklynstore.com.ua/content/images/18/krossovki-muzhskie-reebok-astroride-trail-gtx-2.0-ef4157-94989739737054_small11.webp", 'https://images.prom.ua/2024999788_w640_h640_2024999788.jpg'],
		bunerImg:"",
		material:"leather",
		seasons:["autumn", "spring", "summer", "winter"],
		size:['41', '42', '43'],
		sex:"male",
		color:['white', 'black', 'blue'],
		description:'Product description Reebok Astroride Trail Goretex 2.0 ShoesThese men´s shoes have a durable rubber outsole with a rugged lug pattern for optimal traction in wet or slippery conditions on uneven terrain. The GORE-TEX waterproof lining helps you stay dry and comfortable.',
		price: 210,
		rating: 5,
		category:'sneakers',
		id: 238
	},
	{
		name: "Converse Chuck Taylor All Star",
		imagePath: ['https://kedoff.net/images/product/large/converse-m9160-img-2.jpg', "https://www.skateshop.gr/image/cache/catalog/demo/product/SS19/M9160C_shot2-725x725.jpg", 'https://ultrasport.in.ua/content/images/45/480x320l50nn0/kedy-converse-chuck-taylor-all-star-hi-leather-black-132170c-39566977335415.jpg', "https://obuv24.by/image/cache/catalog/demo/product/converse/a1282%281%29-390x390.jpg" ],
		material:"leather",
		bunerImg:"",
		seasons:["autumn", "spring", "summer", "winter"],
		size:['38', '41', '42', '43'],
		sex:"male",
		color:['white', 'black', 'blue'],
		description:'Product description Reebok Astroride Trail Goretex 2.0 ShoesThese men´s shoes have a durable rubber outsole with a rugged lug pattern for optimal traction in wet or slippery conditions on uneven terrain. The GORE-TEX waterproof lining helps you stay dry and comfortable.',
		price: 90,
		rating: 2.5,
		id: 239
	},
	{
		name: "Lacosta Game Advance Luxe",
		imagePath: ['https://saleusa.com.ua/image/cache/catalog/shoes/9840315/6142353/1-600x450.jpg', 'https://akn-lacoste.b-cdn.net/products/2021/08/11/158047/ba6664a3-a760-4089-b3f3-56924bdc6be9_size2000x2000_cropCenter.jpg', "https://akn-lacoste.b-cdn.net/products/2021/08/11/158047/433d3771-dda3-478c-883d-f04dfcc6acfe_size2000x2000_cropCenter.jpg", "https://saleusa.com.ua/image/cache/catalog/shoes/9840315/6142353/5-600x450.jpg" ],
		material:"leather",
		bunerImg:"",
		seasons:["autumn", "spring", "summer", "winter"],
		size:['38', '41', '42', '43'],
		sex:"male",
		color:['white', 'black', 'blue'],
		description:'Product description Reebok Astroride Trail Goretex 2.0 ShoesThese men´s shoes have a durable rubber outsole with a rugged lug pattern for optimal traction in wet or slippery conditions on uneven terrain. The GORE-TEX waterproof lining helps you stay dry and comfortable.',
		price: 180,
		rating: 3.4,
		category:'sneakers',
		id: 246
	},
	{
		name: "Puma Rebound",
		imagePath: ['https://sportcenterstore.com.ua/assets/images/products/12694/bigwebp/39232609-2.webp', "https://sportcenterstore.com.ua/assets/images/products/12694/bigwebp/39232609-1.webp", 'https://sneakers.by/image/cache/catalog/sneakers-pics/101655/krossovki-puma-rebound-v6-392326-09-8-1000x800.jpg', 'https://i.ebayimg.com/images/g/Kn0AAOSwgYRk7fuc/s-l1200.webp'],
		material:"leather",
		bunerImg:"",
		seasons:["autumn", "spring", "summer", "winter"],
		size:['38', '41', '42', '43'],
		sex:"male",
		color:['white', 'black', 'blue'],
		description:'Product description Reebok Astroride Trail Goretex 2.0 ShoesThese men´s shoes have a durable rubber outsole with a rugged lug pattern for optimal traction in wet or slippery conditions on uneven terrain. The GORE-TEX waterproof lining helps you stay dry and comfortable.',
		price: 110,
		rating: 4.4,
		category:'sneakers',
		id: 256
	},
	{
		name: "Adidas Campus",
		imagePath: ['https://images.deal.by/378956240_krossovki-zhenskie-adidas.jpg', 'https://lishop.store/image/cache/products/2/0/5/adidas-campus-00s-core-black-2-1000x1000.jpg', 'https://idealsport.com.ua/content/images/40/480x480l50nn0/58274202298932.jpeg', 'https://images.shafastatic.net/1552951832'],
		material:"leather",
		bunerImg:"",
		seasons:["autumn", "spring", "summer", "winter"],
		size:['38', '41', '42', '43'],
		sex:"male",
		color:['white', 'black', 'blue'],
		description:'Product description Reebok Astroride Trail Goretex 2.0 ShoesThese men´s shoes have a durable rubber outsole with a rugged lug pattern for optimal traction in wet or slippery conditions on uneven terrain. The GORE-TEX waterproof lining helps you stay dry and comfortable.',
		price: 120,
		rating: 4.4,
		category:'sneakers',
		id: 266
	},
	{
		name: "Adidas Forum Mid Ftw",
		imagePath: ['https://static.ftshp.digital/img/p/1/0/6/4/6/3/2/1064632-full_product.jpg', 'https://img.eobuwie.cloud/eob_product_512w_512h(d/2/5/8/d258c23ef29925fd5fd8573f565079e02eeebe9d_23_4064036984853_rz.jpg,jpg)/vzuttia-adidas-forum-mid-j-fz2083-ftwwht-cblack-ftwwht-0000303317034.jpg', 'https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/55797/uploads/urunresimleri/buyuk/adidas-forum-mid-4c82-8..jpg', 'https://all-stars.by/upload/resize_cache/iblock/d01/fwz00myism0l623b1kc6agn9kof30c2a/457_457_1/FY7939_b.jpg'],
		material:"leather",
		bunerImg: 'https://brand.assets.adidas.com/f_auto,q_auto,fl_lossy/capi/enSG/Images/2021/11/forum-size-guide-masthead-d_207-807066.jpg',
		seasons:["autumn", "spring", "summer", "winter"],
		size:['38', '41', '42', '43'],
		sex:"male",
		color:['white', 'black', 'blue'],
		description:'Product description Reebok Astroride Trail Goretex 2.0 ShoesThese men´s shoes have a durable rubber outsole with a rugged lug pattern for optimal traction in wet or slippery conditions on uneven terrain. The GORE-TEX waterproof lining helps you stay dry and comfortable.',
		price: 100,
		rating: 5,
		category:'sneakers',
		id: 296
	},
	{
		name: "Adidas 4d Futurecraft",
		imagePath: ['https://werare.com.ua/image/cache/webp/catalog/i/mp/nl/a1f2d71defdae4653953a4a9ea5a3c3a-652x733.webp', 'https://werare.com.ua/image/cache/webp/catalog/i/mp/nl/a23e95334d65413e266285c6118b567b-890x1000.webp', 'https://werare.com.ua/image/cache/webp/catalog/i/mp/nl/5953c0840e8dc55f606da2cc38c82b5e-890x1000.webp', 'https://werare.com.ua/image/cache/webp/catalog/i/mp/nl/a23e95334d65413e266285c6118b567b-890x1000.webp'],
		bunerImg:'https://retailers.ua/media/news/1100-s-crop-w/00/05/5319/adi3drunner-770x485-9302.jpg',
		material:"textile",
		seasons:["autumn","summer"],
		size:['42', '43', '44'],
		sex:"male",
		color:['white', 'black'],
		description:'Product description Reebok Astroride Trail Goretex 2.0 ShoesThese men´s shoes have a durable rubber outsole with a rugged lug pattern for optimal traction in wet or slippery conditions on uneven terrain. The GORE-TEX waterproof lining helps you stay dry and comfortable.',
		price: 230,
		rating: 5,
		category:'sneakers',
		id: 299
	},
	{
		name: "Converse Run Star Legacy CX",
		imagePath: ['https://stiliaga.com.ua/pics/prod/big/4236_8421.jpg', 'https://all-stars.by/upload/resize_cache/iblock/dc1/mdgkx2mkf5zl7evchp1mknjppje638t7/457_457_1/A00869C_b.jpg', 'https://static.qns.digital/img/p/2/5/7/3/1/5/8/2573158-full_product.jpg', 'https://cdn.4stand.com/huge/18/c1/18c1b11f59b93cf1cb9fdf166dae6b8526a8053a.jpg'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['36', '39', '37', '41'],
		sex:"female",
		color:['white', 'purple'],
		description:'Converse Run Star Legacy CX was tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 200,
		rating: 3,
		category:'sneakers',
		id: 301
	},
	{
		name: "Converse Pro Blaze",
		imagePath: ['https://converse.ca/media/catalog/product/cache/7675cebc3e2f09ee2a340c17d68ace33/a/0/a04986c_a_107x1.jpg', 'https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw117f30c9/images/g_08/A06391C_G_08X1.jpg', 'https://images.journeys.com/images/products/1_773619_FS.JPG', 'https://d2ob0iztsaxy5v.cloudfront.net/product/570917/5709175320m7_zm.jpg'],
		material:"leather",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['36', '37', '38'],
		sex:"male",
		color:['blue', 'gray'],
		description:'Converse Pro Blaze was tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 190,
		rating: 3.5,
		category:'sneakers',
		id: 302
	},
	{
		name: "Adidas 4DFWD",
		imagePath: ['https://yesoriginal.com.ua/image/cache/catalog/cover/ID3505-472x497.webp', 'https://yesoriginal.com.ua/image/cache/catalog/other_images/ID3505-1-472x497.webp', 'https://yesoriginal.com.ua/image/cache/catalog/other_images/ID3505-3-472x497.webp', 'https://yesoriginal.com.ua/image/cache/catalog/other_images/ID3505-10-472x497.webp'],
		material:"textile",
		bunerImg:"https://www.3dnatives.com/en/wp-content/uploads/sites/2/2021/05/584221_v2.jpg",
		seasons:["autumn","summer"],
		size:['36', '37', '41'],
		sex:"male",
		color:['red', 'black'],
		description:'adidas 4DFWD was tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 210,
		rating: 5,
		category:'sneakers',
		id: 308
	},
	{
		name: "Converse Men's Street Canvas",
		imagePath: ['https://m.media-amazon.com/images/I/41XNjh+qjJL._AC_.jpg', 'https://rmcorp.s3.scarfbot.com/badger/common/photos/products/2017/03/14/a3ba64a171c9ea658d63462c7fe77fa7.jpg', 'https://yesoriginal.com.ua/image/cache/catalog/other_images/A05614C-5-472x497.webp', 'https://yesoriginal.com.ua/image/cache/catalog/i/oe/ng/4353c28f20ea750a3f15c22adf26a518-472x497.webp'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['36', '37', '41'],
		sex:"male",
		color:['black'],
		description:'Converse tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 210,
		rating: 5,
		category:'sneakers',
		id: 303
	},
	{
		name: "Puma Caven 2.0 Mid",
		imagePath: ['https://sportcenterstore.com.ua/assets/images/products/12701/bigwebp/39233302-2.webp', 'https://sportcenterstore.com.ua/assets/images/products/12701/bigwebp/39233302-3.webp', 'https://sportcenterstore.com.ua/assets/images/products/12701/bigwebp/39233302-4.webp', 'https://sportcenterstore.com.ua/assets/images/products/12701/bigwebp/39233302-5.webp'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '42', '43'],
		sex:"male",
		color:['black'],
		description:'Puma Caven 2.0 Mid through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 230,
		rating: 4.5,
		category:'sneakers',
		id: 304
	},
	{
		name: "Adidas Superstar",
		imagePath: ['https://adishop.com.ua/67351-thickbox_default/krossovki-muzhskie-adidas-originals-superstar-eg4958.jpg', 'https://adishop.com.ua/67354-thickbox_default/krossovki-muzhskie-adidas-originals-superstar-eg4958.jpg', 'https://adishop.com.ua/67353-large_default/krossovki-muzhskie-adidas-originals-superstar-eg4958.jpg', 'https://adishop.com.ua/67354-thickbox_default/krossovki-muzhskie-adidas-originals-superstar-eg4958.jpg'],
		material:"leather",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:[ '41', '43', '44'],
		sex:"male",
		color:['white'],
		description:'Adidas was tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 130,
		rating: 4.5,
		category:'sneakers',
		id: 3021
	},
	{
		name: "Puma Pokemon",
		imagePath: ["https://i.ebayimg.com/images/g/DtMAAOSwxxFjfK2S/s-l1200.webp" ,'https://i.ebayimg.com/images/g/SJMAAOSwklBlH53P/s-l1200.jpg', 'https://i.ebayimg.com/thumbs/images/g/cgsAAOSwYThj0iDA/s-l640.jpg', 'https://idealsport.com.ua/content/images/10/480x480l50nn0/97371323024877.jpeg'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['36', '37'],
		sex:"male",
		color:['red', 'orange'],
		description:'Puma Cruis Rider was tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 270,
		rating: 5,
		category:'sneakers',
		id: 305
	},
	{
		name: "Reebok Rebound v6 Sneakers Senior",
		imagePath: ['https://www.reebok.in.ua/image/cache/catalog/img_products/12_2023/100001300_01-700x700.jpg', 'https://www.reebok.in.ua/image/cache/catalog/img_products/12_2023/100001300_05-700x700.jpg', 'https://www.reebok.in.ua/image/cache/catalog/img_products/12_2023/100001300_03-700x700.jpg', 'https://www.reebok.in.ua/image/cache/catalog/img_products/12_2023/100001300_04-700x700.jpg'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '43', '44'],
		sex:"male",
		color:['gray'],
		description:'adidas 4DFWD was tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 150,
		rating: 5,
		category:'sneakers',
		id: 3022
	},
	
	{
		name: "Puma Rebound v6 Sneakers Senior",
		imagePath: ['https://cdn.plutosport.com/m/catalog/product/P/u/Puma-Rebound-v6-Sneakers-Senior-2308011443.jpg', 'https://cdn.plutosport.com/m/catalog/product/P/u/Puma-Rebound-v6-Sneakers-Senior_4-2308011443.jpg', 'https://cdn.plutosport.com/m/catalog/product/P/u/Puma-Rebound-v6-Sneakers-Senior_3-2308011443.jpg', 'https://cdn.plutosport.com/m/catalog/product/P/u/Puma-Rebound-v6-Sneakers-Senior_2-2308011443.jpg'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '43', '44'],
		sex:"male",
		color:['gray'],
		description:'adidas 4DFWD was tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 150,
		rating: 5,
		category:'sneakers',
		id: 307
	},
	{
		name: "Lacosta Synthetic Sneakers",
		imagePath: ['https://rustans.com/cdn/shop/files/3133764_01.jpg', 'https://rustans.com/cdn/shop/files/3133764_02.jpg', 'https://rustans.com/cdn/shop/files/3133764_05.jpg', 'https://rustans.com/cdn/shop/files/3133764_04.jpg'],
		material:"leather",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['39', '41', '44'],
		sex:"male",
		color:['white'],
		description:'Lacosta Synthetic Sneakers through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 180,
		rating: 5,
		category:'sneakers',
		id: 3033
	},
	{
		name: "Nike Nike Dunk High",
		imagePath: ['https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/99486859-0ff3-46b4-949b-2d16af2ad421/custom-nike-dunk-high-by-you-shoes.png', 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/5f054da9-907a-4153-a025-48bb64bf8520/custom-nike-dunk-high-by-you-shoes.png', 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/cbddd67b-444b-4a7c-b458-20643ab89b1b/custom-nike-dunk-high-by-you-shoes.png', 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/39c54a4a-bcff-4aaf-b599-3cd07b8a0a05/custom-nike-dunk-high-by-you-shoes.png'],
		material:"leather",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '43', '44'],
		sex:"male",
		color:['blue'],
		description:'Nike Dunk High tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 200,
		rating: 5,
		category:'sneakers',
		id: 3034
	},
	{
		name: "Lacosta AG-LT 23 Ultra AC",
		imagePath: ['https://img.tenniswarehouse-europe.com/watermark/rs.php?path=LMUAGW-1.jpg', 'https://img.tenniswarehouse-europe.com/watermark/rs.php?path=LMUAGW-3.jpg', 'https://img.tenniswarehouse-europe.com/watermark/rs.php?path=LMUAGW-4.jpg', 'https://img.tenniswarehouse-europe.com/watermark/rs.php?path=LMUAGW-5.jpg'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '43', '44'],
		sex:"male",
		color:['green'],
		description:'acosta AG-LT 23 Ultra AC procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 170,
		rating: 5,
		category:'sneakers',
		id: 3037
	},
	{
		name: "Adidas Cyber System",
		imagePath: ['https://www.buzzsneakers.gr/files/thumbs/files/images/slike_proizvoda/media/GX2/GX2023/images/thumbs_900/GX2023_900_900px.jpg', 'https://www.buzzsneakers.gr/files/thumbs/files/images/slike_proizvoda/media/GX2/GX2023/images/thumbs_900/GX2023_1_900_900px.jpg', 'https://www.buzzsneakers.gr/files/thumbs/files/images/slike_proizvoda/media/GX2/GX2023/images/thumbs_900/GX2023_3_900_900px.jpg', 'https://www.buzzsneakers.gr/files/thumbs/files/images/slike_proizvoda/media/GX2/GX2023/images/thumbs_900/GX2023_4_900_900px.jpg'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '43', '44'],
		sex:"male",
		color:['gray'],
		description:'adidas 4DFWD was tested through a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 250,
		rating: 4.6,
		category:'sneakers',
		id: 3038
	},
	{
		name: "Nike Comics Sun",
		imagePath: ['https://www.mimanerashop.com/images/nike-customizzata-comics-gialla-arancio-sneakers-d.1200x1200.10465.webp', 'https://www.mimanerashop.com/images/nike-comics-sun.1200x1200.10467.webp', 'https://www.mimanerashop.com/images/nike-comics-sun.1200x1200.10468.webp', 'https://www.mimanerashop.com/images/nike-comics-sun.1200x1200.10470.webp'],
		material:"leather",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '43', '44'],
		sex:"male",
		color:['orange'],
		description:'Nike Comics Sun a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 290,
		rating: 4.2,
		category:'sneakers',
		id: 3044
	},
	{
		name: "Vans Knu Skool",
		imagePath: ['https://yesoriginal.com.ua/image/cache/catalog/cover/VN0009QC6RT-472x497.webp', 'https://yesoriginal.com.ua/image/cache/catalog/other_images/VN0009QC6RT-3-472x497.webp', 'https://yesoriginal.com.ua/image/cache/catalog/other_images/VN0009QC6RT-4-472x497.webp', 'https://yesoriginal.com.ua/image/cache/catalog/other_images/VN0009QC6RT-5-472x497.webp'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['38', '40', '44'],
		sex:"male",
		color:['red'],
		description:'Vans Knu Skool which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 120,
		rating: 3.2,
		category:'sneakers',
		id: 3045
	},
	{
		name: "U.S.-Polo Nobil1",
		imagePath: ['https://www.runner.com.eg/cdn/shop/products/1_366ac46c-b8bb-4973-90c1-089a2c884dd2.jpg', 'https://www.runner.com.eg/cdn/shop/products/5_a3635343-af3e-497e-bfda-112be35a3bbd.jpg', 'https://www.runner.com.eg/cdn/shop/products/6_5cc1525f-2f86-40cc-bf25-234550711a62.jpg', 'https://www.runner.com.eg/cdn/shop/products/4_5b8e86fe-3bbb-4d83-a6b0-616dedfc2afc.jpg'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '43', '44'],
		sex:"male",
		color:['white', 'blue'],
		description:'U.S.-Polo Nobil1 procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 300,
		rating: 4.7,
		category:'sneakers',
		id: 3050
	},
	{
		name: "Vans Classic High",
		imagePath: ['https://vans.org.ua/image/cache/catalog/obuv/6/com-mnresize-1500-1500-Content-media-ProductImg-original-637639372664654845-600x600.jpg', 'https://vans.org.ua/image/cache/catalog/obuv/6/com-mnresize-1500-1500-Content-media-ProductImg-original-637639372685835723-600x600.jpg', 'https://vans.org.ua/image/cache/catalog/obuv/6/com-mnresize-1500-1500-Content-media-ProductImg-original-637639372706614212-600x600.jpg', 'https://vans.org.ua/image/cache/catalog/obuv/6/com-mnresize-1500-1500-Content-media-ProductImg-original-637639372675081191-600x600.jpg'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '43', '44'],
		sex:"male",
		color:['black'],
		description:'Vans a range of bio-mechanical testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 110,
		rating: 3.2,
		category:'sneakers',
		id: 3047
	},
	{
		name: "Reebok Royal BB4500 HI2",
		imagePath: ['https://img.eobuwie.cloud/eob_product_512w_512h(b/3/8/5/b385293ad589097610fb4435e5d9900794959893_30_5905588474623_bs.jpg,webp)/vzuttia-reebok-royal-bb4500-hi2-100074732-white-5905588474623.webp', 'https://img.eobuwie.cloud/eob_product_1800w_1800h(1/3/b/d/13bd4a1d3a5a33edf23d82ad51e76e52a9bf094c_21_5905588474623_bs.jpg,webp)/vzuttia-reebok-royal-bb4500-hi2-100074732-white-5905588474623.webp', 'https://img.eobuwie.cloud/eob_product_1800w_1800h(2/c/0/1/2c01edfd94f9a6352717306a8f83f65442a1b344_25_5905588474623_bs.jpg,webp)/vzuttia-reebok-royal-bb4500-hi2-100074732-white-5905588474623.webp', 'https://img.eobuwie.cloud/eob_product_512w_512h(9/c/a/0/9ca0de560fa854e7f8222c9e3bf18bd9c82ae72c_26_5905588474623_bs.jpg,webp)/vzuttia-reebok-royal-bb4500-hi2-100074732-white-5905588474623.webp'],
		material:"textile",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['41', '43', '44'],
		sex:"male",
		color:['blue'],
		description:'Reebok Royal BB4500 HI2 testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 310,
		rating: 5,
		category:'sneakers',
		id: 3048
	},
	{
		name: "Adidas Essentials",
		imagePath: ['https://m.media-amazon.com/images/I/51wDM5KX9+L._AC_SX569_.jpg', 'https://m.media-amazon.com/images/I/51lZ6tF44mL._AC_SX569_.jpg', 'https://m.media-amazon.com/images/I/51ODMTj7uoL._AC_SX569_.jpg', 'https://m.media-amazon.com/images/I/51I2xWTY6+L._AC_SX569_.jpg'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['XXL', 'XL', 'M'],
		sex:"male",
		color:['blue', 'green', 'white'],
		description:'Reebok Royal BB4500 HI2 testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 70,
		rating: 3.2,
		category:"tshirts",
		id: 1012
	},
	{
		name: "Nike Men's T-Shirt",
		imagePath: ['https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/df30d548-173e-4665-8d14-029fa108a97e/sportswear-club-t-shirt-bVD3j8.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f4ca48e9-1813-40e6-858d-f9980a8b09e9/sportswear-club-t-shirt-bVD3j8.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f915359e-e43e-4a8a-925b-0aab42c0556c/sportswear-club-t-shirt-bVD3j8.png', 'hhttps://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2caaec1a-3594-4030-aceb-da4fd1bbed97/sportswear-club-t-shirt-bVD3j8.png'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['2XL', 'XL', 'M'],
		sex:"male",
		color:['white'],
		description:'Nike BB4500 HI2 testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 120,
		rating: 5,
		category:"tshirts",
		id: 1013
	},
	{
		name: "Jordan Flight Essentials",
		imagePath: ['https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/0452949f-538d-4f9a-a363-9fcd5ab3c506/jordan-flight-essentials-t-shirt-7Cvcwd.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/35ddf9b8-ae24-435f-a6b1-2482e0efa8b7/jordan-flight-essentials-t-shirt-7Cvcwd.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/4ae129be-6aa9-465b-9d88-5fe679e8503b/jordan-flight-essentials-t-shirt-7Cvcwd.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/be8d6b10-ccb6-460c-bfae-5a92773a50bf/jordan-flight-essentials-t-shirt-7Cvcwd.png'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['XXL', 'XL', 'M', 'S', 'L'],
		sex:"male",
		color:['blue', 'white'],
		description:'Jordan Flight Essentials testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 80,
		rating: 4.2,
		category:"tshirts",
		id: 1014
	},
	{
		name: "Reebok Large Logo T-Shirt",
		imagePath: ['https://i8.amplience.net/i/jpl/jd_676518_a?qlt=92&w=750&h=957&v=1&fmt=auto', 'https://i8.amplience.net/i/jpl/jd_676518_b?qlt=92&w=750&h=957&v=1&fmt=auto', 'https://i8.amplience.net/i/jpl/jd_676518_c?qlt=92&w=750&h=957&v=1&fmt=auto', 'https://i8.amplience.net/i/jpl/jd_676518_d?qlt=92&w=750&h=957&v=1&fmt=auto'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['L', 'S', 'M'],
		sex:"male",
		color:['white'],
		description:'Reebok Large Logo T-Shirt testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 90,
		rating: 3.2,
		category:"tshirts",
		id: 1015
	},
	{
		name: "Adidas Essentials 3",
		imagePath: ['https://xcdn.next.co.uk/COMMON/Items/Default/Default/ItemImages/AltItemShot/315x472/C76427s.jpg', 'https://xcdn.next.co.uk/COMMON/Items/Default/Default/ItemImages/AltItemShot/315x472/C76427s2.jpg', 'https://xcdn.next.co.uk/COMMON/Items/Default/Default/ItemImages/AltItemShot/315x472/C76427s3.jpg', 'https://xcdn.next.co.uk/COMMON/Items/Default/Default/ItemImages/AltItemShot/315x472/C76427s4.jpg'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['S', 'L', 'M'],
		sex:"male",
		color:['blue', 'green', 'white'],
		description:'Adidas Essentials 3 testing procedures at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 30,
		rating: 4.2,
		category:"tshirts",
		id: 1016
	},
	{
		name: "Reebok CL Graphic",
		imagePath: ['https://static.qns.digital/img/p/1/2/8/5/9/5/4/1285954.jpg', 'https://static.qns.digital/img/p/1/2/8/5/9/5/1/1285951.jpg', 'https://static.qns.digital/img/p/1/2/8/5/9/5/7/1285957.jpg', 'https://static.qns.digital/img/p/1/2/8/5/9/5/4/1285954.jpg'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['S', 'L', 'M'],
		sex:"male",
		color:['green', 'white'],
		description:'Reebok CL Graphics at the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 40,
		rating: 5,
		category:"tshirts",
		id: 1017
	},
	{
		name: "Reebok Men T-Shirt",
		imagePath: ['https://m.media-amazon.com/images/I/61yglB6+tOL._SY741_.jpg', 'https://m.media-amazon.com/images/I/517cfeB-YOL._SY741_.jpg', 'https://m.media-amazon.com/images/I/61Jxupwru5L._SY741_.jpg', 'https://m.media-amazon.com/images/I/61kFL5XBWxL._SY741_.jpg'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['L', 'M', "XXL"],
		sex:"male",
		color:['white'],
		description:'Reebok Men T-Shirt the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 60,
		rating: 5,
		category:"tshirts",
		id: 1018
	},
	{
		name: "U.S-Polo Assn 88",
		imagePath: ['https://photos6.spartoo.com/photos/264/26495003/26495003_1200_C.jpg', 'https://photos6.spartoo.com/photos/264/26495003/26495003_1200_B.jpg', 'https://photos6.spartoo.com/photos/264/26495003/26495003_1200_A.jpg', 'https://photos6.spartoo.com/photos/264/26495003/26495003_1200_C.jpg'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['L', 'M', "XXL"],
		sex:"male",
		color:['white'],
		description:'U.S-Polo Assn 88 the University of Calgary, which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 65,
		rating: 4,
		category:"tshirts",
		id: 1019
	},
	{
		name: "Nike Core T-Shirt",
		imagePath: ['https://i8.amplience.net/i/jpl/jd_668572_a?qlt=92&w=750&h=957&v=1&fmt=auto', 'https://i8.amplience.net/i/jpl/jd_668572_b?qlt=92&w=750&h=957&v=1&fmt=auto', 'https://i8.amplience.net/i/jpl/jd_668572_c?qlt=92&w=750&h=957&v=1&fmt=auto', 'https://i8.amplience.net/i/jpl/jd_668572_d?qlt=92&w=750&h=957&v=1&fmt=auto'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['L', 'M', "XXL"],
		sex:"male",
		color:['purple'],
		description:'Nike Core T-Shirt which analysed specific areas such as forward motion, braking force and running economy. The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 30,
		rating: 5,
		category:"tshirts",
		id: 1020
	},
	{
		name: "Jordan Flight MVP",
		imagePath: ['https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/a9eb236c-c109-4015-b133-878d3f742a43/jordan-flight-mvp-t-shirt-t82FXJ.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/e88ebb1e-2410-49f6-9654-9719c44dc8ff/jordan-flight-mvp-t-shirt-t82FXJ.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/28c03717-5e49-49bf-8648-68d4ff79abb4/jordan-flight-mvp-t-shirt-t82FXJ.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/0c587b4d-7c14-4950-a225-c4952c87e9aa/jordan-flight-mvp-t-shirt-t82FXJ.png'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['L', 'M', "XXL"],
		sex:"male",
		color:['white'],
		description:'The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 30,
		rating: 3.5,
		category:"tshirts",
		id: 1021
	},
	{
		name: "Lacosta T-shirt SA",
		imagePath: ['https://static.qns.digital/img/p/1/3/4/8/1/1/7/1348117.jpg', 'https://static.qns.digital/img/p/1/3/4/8/1/2/0/1348120.jpg', 'https://static.qns.digital/img/p/1/3/4/8/1/2/3/1348123.jpg', 'https://static.qns.digital/img/p/1/3/4/8/1/1/7/1348117.jpg'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['L', 'M', "XXL"],
		sex:"male",
		color:['black'],
		description:'The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 30,
		rating: 4,
		category:"tshirts",
		id: 1022
	},
	{
		name: "Adidas Men's Sports ",
		imagePath: ['https://m.media-amazon.com/images/I/411B+rGRKFL._AC_SX569_.jpg', 'https://m.media-amazon.com/images/I/51oczyl-FTL._AC_SY606_.jpg', 'https://m.media-amazon.com/images/I/51bCPcuOo1L._AC_SY606_.jpg', 'https://m.media-amazon.com/images/I/51J2pOmX9PL._AC_SY606_.jpg'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['L', 'M', "XXL"],
		sex:"male",
		color:['black', 'blue', 'white'],
		description:'The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 30,
		rating: 3.5,
		category:"tshirts",
		id: 1023
	},
	{
		name: "Nike Long-Sleeve",
		imagePath: ['https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7227374e-7ec2-40c1-963f-ad92fd261e4a/sportswear-mens-long-sleeve-t-shirt-qwrWHM.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/55eba64d-0bc9-4caf-884d-2415c02356d1/sportswear-mens-long-sleeve-t-shirt-qwrWHM.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6ff5348c-9b36-4533-8694-5e2fba2b3d36/sportswear-mens-long-sleeve-t-shirt-qwrWHM.png', 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/18c7ec2c-84d6-4ca4-a4e4-813ed23e3675/sportswear-mens-long-sleeve-t-shirt-qwrWHM.png'],
		material:"100% Cotton",
		bunerImg:"",
		seasons:["autumn","summer"],
		size:['L', 'M', "XXL"],
		sex:"male",
		color:['purple'],
		description:'The concept was also tested extensively with adidas runners local to the creation team in Germany and a carefully selected cohort of high-level running creators across the USA.',
		price: 40,
		rating: 4.5,
		category:"tshirts",
		id: 1024
	},


]

const dataCounrty = [
	{
		countryName: 'Ukraine',
		cityName: ['Kiev', 'Herson', 'Borispol', 'Odessa', 'Harkov', 'Doneck', 'Rivne', 'Lviv', 'Dnepr']
	},
	{
		countryName: 'USA',
		cityName: ['New York', 'Los Angeles', 'Alabama', 'Washington', 'Denver', 'Honolulu', 'Sacramento']
	},
	{
		countryName: 'Fracne',
		cityName: ['Paris', 'Marseille', 'Reno', 'Lyon', 'Rennes', 'Grenoble', 'Dijon']
	},
	{
		countryName: 'Germany',
		cityName: ['Berlin', 'Hamburg', 'Rammstein', 'Stuttgart', 'Dortmund', 'Bremen', 'Dresden']
	},
	{
		countryName: 'Italy',
		cityName: ['Rome', 'Naples', 'Palermo', 'Catania', 'Venice', '	Messina', 'Padua']
	},

];

export default dataCounrty;